# Generated by Django 4.1.6 on 2023-04-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_order_id_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product_model',
            name='deal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
