# Generated by Django 4.1.6 on 2023-05-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_model_deal_product_model_deal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='product_model',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='projects/'),
        ),
    ]
