# Generated by Django 4.1.6 on 2023-05-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='product_model',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product_category'),
        ),
    ]
